plugins = []
headers = []
redirects = []

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[functions."*"]

[build]
  publish = "public"
  NODE_VERSION = "18"
 

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]